### ISSUE TITLE
Fix internal links by updating config.toml

### ISSUE THREAD

**Issue by bast** [coderefinery/2022-09-20-workshop#6]

**Comment by MatiasJJ** [comment]
I went through the links and for the most part it is fine. I wanted to write things down before checking out how to actually edit stuff here.

• In https://coderefinery.github.io/2022-09-20-workshop/ News section: You can sign up [here](https://coderefinery.org/workshops/upcoming/#notify-me) could lead to https://indico.neic.no/event/135/surveys/36 instead
• in https://coderefinery.github.io/2022-09-20-workshop/volunteer/ this link is not found https://coderefinery.github.io/manuals/helper-intro/ is not found

**Comment by bast** [comment]
Thanks for identifying these! Are you planning to fix these links? No pressure to, only to be clear on who is working on it.

**Comment by MatiasJJ** [comment]
I could but I don't know correct alternative, sorry.

**Comment by bast** [comment]
OK I will look and fix.
